### PR TITLE
Updated To Kibana 6.5.1

### PR DESCRIPTION
**Pull request by anomaliyao**
After updating the kibana on 6.5.1, an error occurred in the plug-in.
The error is that when hidden aggregation metrics the formula does not work.
image

When metrics are not hidden
image

Help please solve this problem? Now it is very important for our project.

### CODE REVIEW

**Comment by pchakour** [comment]
Hello @anomaliyao !
This not a PullRequest but an issue here !
Kibana 6.5.1 is not supported yet by the official team. If you want fix this bug you have to replace the **line 10** of the file **kibana-datasweet-formula/public/decorators/lib/apply_hidden.js** with the following line : 
`table.rows = reject(table.rows, (r, i) => includes(hiddenCols, i));`

**Comment by anomaliyao** [comment]
Made code changes.
Now, trying to hide the aggregation, it works successfully, if only to hide the aggregation using the plugin datasweet.
If  hide a custom aggregation (Sum), the formula stops working and nothing is shown.
image

**Comment by pchakour** [comment]
Weird ! I did the same thing and it's working. Are you sure that you have data in your time range ?

**Comment by pchakour** [comment]
Ok, I found the problem. On the new version of kibana, if the metric is hidden and if where is no bucket, kibana return no data for the metric. So, you have to create a bucket to make this work. In the following screenshot, I use a filter bucket.

capture du 2018-12-17 10-49-20

**Comment by anomaliyao** [comment]
This is very similar to the fact that by adding such a hack, the loading time of the metric increases over a long time interval. Maybe can fix it somehow or create issue?

**Comment by pchakour** [comment]
> Maybe can fix it somehow or create issue?

I let the team decide :) 
But the team needs time so you have to work with this tips until the new release

**Comment by anomaliyao** [comment]
Is it not a kibana bug?
Are you from the datasweet formula plugin team?

**Comment by pchakour** [comment]
> Is it not a kibana bug?
I don't think, it's a new response format from kibana

> Are you from the datasweet formula plugin team?
No, I'm a user like you ;)

**Comment by tcharlot-datasweet** [comment]
Try last release

**Pull request closed without merging**
