### PR TITLE
Kibana 6.4.x upgrade

### LINKED ISSUE #26: "Incorrect Kibana version in plugin [datasweet_formula]. Expected [6.4.0]; found [6.3.2]"
When did you release the version of datasweet_formula for Kibana  6.4

actually we have:

./bin/kibana-plugin  install  https://github.com/datasweet/kibana-datasweet-formula/releases/download/1.1.0/datasweet_formula-1.1.0_kibana-6.3.2.zip
Attempting to transfer from https://github.com/datasweet/kibana-datasweet-formula/releases/download/1.1.0/datasweet_formula-1.1.0_kibana-6.3.2.zip
Transferring 402149 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [datasweet_formula]. Expected [6.4.0]; found [6.3.2]"

### PR DESCRIPTION
**Pull request by gmatheus**
Upgrading **Datasweet Formula** for Kibana `6.4.x`.

Closes #26

Main changes:
- [x] Project structure changed due to new [Kibana Plugin Generator](https://github.com/elastic/kibana/tree/v6.4.0/packages/kbn-plugin-generator)
- [x] `Private` injector changed in some module imports (see [Plugin API Changes in 6.4](https://www.elastic.co/blog/upcoming-kibana-plugin-api-changes-in-6-4))
- [x] `applyColumnGroups` params changed
- [x] ESLint config added and code style fixed

To run the project using the scripts provided by [Kibana Plugin Generator](https://github.com/elastic/kibana/tree/v6.4.0/packages/kbn-plugin-generator), you should place this plugin inside `../kibana-extra` folder, then run `yarn kbn bootstrap` and `yarn start`.

Since this is a big change in project structure, I suggest you to organize plugin releases versions by Kibana versions ([just as I did in my plugin](https://github.com/belugadb/kibana-comparable-time-range/blob/ed7b9100afe37201b9b50b8f3cf0ee7df67e69f7/README.md#installation)). E.g.: Datasweet Formula's `v1.1.1` plugin works for Kibana versions from `5.6.x` to `6.3.x`, version `v1.2.0` works for Kibana `6.4.x`. What do you think, @tcharlot-datasweet?

### CODE REVIEW

**Comment by tcharlot-datasweet** [comment]
Hi @gmatheus 
Thx for your PR :+1: !
Just one question : i guess with your changes, the plugin can't be updated for previous version of kibana ?

**Comment by gmatheus** [comment]
@tcharlot-datasweet That's right. This is mainly because Elastic team updated the [plugin development scripts](https://github.com/elastic/kibana/tree/master/packages/kbn-plugin-generator#plugin-development-scripts) since Kibana `6.3`. The `plugin-helpers` dependency is now a package inside `../../kibana/packages`, so, to run/build the project, you must have an updated Kibana copy inside parent folder.

They also removed some Angular services and changed some classes from Kibana source code, so we had to refactor some imports (just as you did in the first commit of this PR). In the long term, this can generate a lot of conditional-versioning logic in the code.

If you organize plugin releases versions as I mentioned above, sometimes you can backport a feature or bugfix through versions. Example:

* Imagine you have `master` branch and `v1.1.x` branch. Master is for Kibana `6.4.x` and `v1.1.x` branch is for Kibana `5.6.x` ~ `6.3.x` versions.
* Some bugfix is pushed to master. You can backport it if needed:
```
git checkout v1.1.x
git cherry-pick <commit from master>
```
This applies the bugfix commit from `master` into `v1.1.x` branch!

If your team depends directly on previous versions of Kibana, you can do the opposite: set the `master` branch to point to the current version of plugin and create a new branch to handle `6.4.x` version and future updates. In this case, this PR should target your `6.4.x` branch instead of `master`. What do you think?

**Comment by tcharlot-datasweet** [comment]
Hi @gmatheus 
Can u fix your PR ? I will create a new branch v1 for old kibana (<= 6.3.x) and merge your changes into master.
Thx for your time 👍

**Comment by gmatheus** [comment]
@tcharlot-datasweet Conflicts resolved! Please wait a little bit to merge this one, I just noticed an error while using the Formula Plugin with **"other values"** feature (from terms bucket aggregation):

image

image

I'll try to fix this in the next days!

**Comment by tcharlot-datasweet** [comment]
Ok 👍 
Thx :)

**Comment by gmatheus** [comment]
Just realized this is not a plugin-related bug (see [this issue](https://github.com/elastic/kibana/issues/24115)), so I guess we're ready merge this PR!

**Comment by lcheryl** [comment]
@tcharlot-datasweet , do you plan to merge this PR and release it soon? We migrated Kibana to 6.4 and datasweet plugin is not working now. It would be very helpful if this fix releases. Thanks in advance and great work!

**Pull request merged**
